apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api-container
          image: kirangothe/userpost-api:latest
          ports:
            - containerPort: 9000  
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-deployment
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000 
  type: LoadBalancer