apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      containers:
        - name: eureka-container
          image: kirangothe/userpost-eureka:latest
          ports:
            - containerPort: 8999  
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-deployment
  ports:
    - protocol: TCP
      port: 8999
      targetPort: 8999 
  type: LoadBalancer