apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: post-deployment
    spec:
      containers:
        - name: post-container
          image: kirangothe/userpost-post:latest
          ports:
            - containerPort: 8085  
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30020
  type: NodePort