apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-container
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-container
    spec:
      containers:
        - name: user-container
          image: kirangothe/userpost-user:latest
          ports:
            - containerPort: 8087  
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-container
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
      nodePort: 30030
  type: NodePort