server:
  port: 8087

spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://13.238.86.167:8999/eureka/
  instance:
    hostname: 13.238.86.167

management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuit-breaker:
    instances:
      user-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 6
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED